### ISSUE TITLE
Segfault when trying to write a token starting with .

### ISSUE THREAD

**Issue by sikthehedgehog** [Clownacy/clownassembler#16]
Helping somebody figure out why his code doesn't work and he wrote `.include` instead of `include` (oops). The bug report here is that clownassembler crashes with a segfault instead of reporting an error as expected.

Tried further with bogus keywords…

This doesn't segfault (just reports an error as expected):
```
    word 1
```
This does segfault:
```
    .word 1
```
So the problem seems to be tokens that start with a `.` (in fact, `.` on its own also segfaults)

**Comment by Clownacy** [comment]
Thanks for reporting that bug! It seems that the crash only occurs if the directive occurs before any labels.
