### ISSUE TITLE
Assembler pads output with zeros when setting ORG.

### ISSUE THREAD

**Issue by daschewie** [Clownacy/clownassembler#6]
## Issue
Assembling the following with `clownassembler -i hello.s -o hello.pgx -l hello.lst` produces a 64k binary pre-padded with zeros:
```asm
;;;
;;; Sample PGX Program
;;;

                org $010000

                dc.b "PGX", $02
                dc.l start

start:          move.l #$13,d0                      ; sys_chan_write
                clr.l d1                            ; Channel #0
                move.l #greet,d2                    ; Pointer to message
                move.l #greet_end-greet+1,d3        ; Length of message
                trap #15

done:           clr.l d0                            ; sys_exit
                clr.l d1                            ; Return value = 0
                trap #15

greet:          dc.b "Hello, world!"
greet_end:      dc.b 0
```

The same code assembled with `vasmm68k_mot -Fbin -L hello.lst -o hello.pgx hello.s` produces a 42b binary.

## Request
Could an option be added to strip the pre-padding?

**Comment by Clownacy** [comment]
Thanks for finding this. asm68k, which is the assembler that this assembler aims from drop-in compatibility with, avoids pre-padding too, so my emulator not doing this was a bug.
